/**
 * Auto-generated by scripts/generate-locations.mjs
 * Source: uetds.uab.gov.tr -> ilce-listesi.xlsx (columns: IL_ADI, AD)
 */
export const CITIES = [
  {
    "id": "adana",
    "name": "Adana",
    "districts": [
      "Aladağ",
      "Ceyhan",
      "Çukurova",
      "Feke",
      "İ̇mamoğlu",
      "Karai̇sali",
      "Karataş",
      "Kozan",
      "Pozanti",
      "Sai̇mbeyli̇",
      "Sariçam",
      "Seyhan",
      "Tufanbeyli̇",
      "Yumurtalik",
      "Yüreği̇r"
    ]
  },
  {
    "id": "adiyaman",
    "name": "Adiyaman",
    "districts": [
      "Besni̇",
      "Çeli̇khan",
      "Gerger",
      "Gölbaşi",
      "Kahta",
      "Merkez",
      "Samsat",
      "Si̇nci̇k",
      "Tut"
    ]
  },
  {
    "id": "afyonkarahi-sar",
    "name": "Afyonkarahi̇sar",
    "districts": [
      "Başmakçi",
      "Bayat",
      "Bolvadi̇n",
      "Çay",
      "Çobanlar",
      "Dazkiri",
      "Di̇nar",
      "Emi̇rdağ",
      "Evci̇ler",
      "Hocalar",
      "İ̇hsani̇ye",
      "İ̇scehi̇sar",
      "Kizilören",
      "Merkez",
      "Sandikli",
      "Si̇nanpaşa",
      "Sultandaği",
      "Şuhut"
    ]
  },
  {
    "id": "agri",
    "name": "Ağri",
    "districts": [
      "Di̇yadi̇n",
      "Doğubayazit",
      "Eleşki̇rt",
      "Hamur",
      "Merkez",
      "Patnos",
      "Taşliçay",
      "Tutak"
    ]
  },
  {
    "id": "aksaray",
    "name": "Aksaray",
    "districts": [
      "Ağaçören",
      "Eski̇l",
      "Gülağaç",
      "Güzelyurt",
      "Merkez",
      "Ortaköy",
      "Sariyahşi̇",
      "Sultanhani"
    ]
  },
  {
    "id": "amasya",
    "name": "Amasya",
    "districts": [
      "Göynücek",
      "Gümüşhaciköy",
      "Hamamözü",
      "Merkez",
      "Merzi̇fon",
      "Suluova",
      "Taşova"
    ]
  },
  {
    "id": "ankara",
    "name": "Ankara",
    "districts": [
      "Akyurt",
      "Altindağ",
      "Ayaş",
      "Bala",
      "Beypazari",
      "Çamlidere",
      "Çankaya",
      "Çubuk",
      "Elmadağ",
      "Eti̇mesgut",
      "Evren",
      "Gölbaşi",
      "Güdül",
      "Haymana",
      "Kahramankazan",
      "Kaleci̇k",
      "Keçi̇ören",
      "Kizilcahamam",
      "Mamak",
      "Nallihan",
      "Polatli",
      "Pursaklar",
      "Si̇ncan",
      "Şerefli̇koçhi̇sar",
      "Yeni̇mahalle"
    ]
  },
  {
    "id": "antalya",
    "name": "Antalya",
    "districts": [
      "Akseki̇",
      "Aksu",
      "Alanya",
      "Demre",
      "Döşemealti",
      "Elmali",
      "Fi̇ni̇ke",
      "Gazi̇paşa",
      "Gündoğmuş",
      "İ̇bradi",
      "Kaş",
      "Kemer",
      "Kepez",
      "Konyaalti",
      "Korkuteli̇",
      "Kumluca",
      "Manavgat",
      "Merkez",
      "Muratpaşa",
      "Seri̇k"
    ]
  },
  {
    "id": "ardahan",
    "name": "Ardahan",
    "districts": [
      "Çildir",
      "Damal",
      "Göle",
      "Hanak",
      "Merkez",
      "Posof"
    ]
  },
  {
    "id": "artvi-n",
    "name": "Artvi̇n",
    "districts": [
      "Ardanuç",
      "Arhavi̇",
      "Borçka",
      "Hopa",
      "Kemalpaşa",
      "Merkez",
      "Murgul",
      "Şavşat",
      "Yusufeli̇"
    ]
  },
  {
    "id": "aydin",
    "name": "Aydin",
    "districts": [
      "Bozdoğan",
      "Buharkent",
      "Çi̇ne",
      "Di̇di̇m",
      "Efeler",
      "Germenci̇k",
      "İ̇nci̇rli̇ova",
      "Karacasu",
      "Karpuzlu",
      "Koçarli",
      "Köşk",
      "Kuşadasi",
      "Kuyucak",
      "Merkez",
      "Nazi̇lli̇",
      "Söke",
      "Sultanhi̇sar",
      "Yeni̇pazar"
    ]
  },
  {
    "id": "balikesi-r",
    "name": "Balikesi̇r",
    "districts": [
      "Altieylül",
      "Ayvalik",
      "Balya",
      "Bandirma",
      "Bi̇gadi̇ç",
      "Burhani̇ye",
      "Dursunbey",
      "Edremi̇t",
      "Erdek",
      "Gömeç",
      "Gönen",
      "Havran",
      "İ̇vri̇ndi̇",
      "Karesi̇",
      "Kepsut",
      "Manyas",
      "Marmara",
      "Merkez",
      "Savaştepe",
      "Sindirgi",
      "Susurluk"
    ]
  },
  {
    "id": "bartin",
    "name": "Bartin",
    "districts": [
      "Amasra",
      "Kurucaşi̇le",
      "Merkez",
      "Ulus"
    ]
  },
  {
    "id": "batman",
    "name": "Batman",
    "districts": [
      "Beşi̇ri̇",
      "Gercüş",
      "Hasankeyf",
      "Kozluk",
      "Merkez",
      "Sason"
    ]
  },
  {
    "id": "bayburt",
    "name": "Bayburt",
    "districts": [
      "Aydintepe",
      "Demi̇rözü",
      "Merkez"
    ]
  },
  {
    "id": "bi-leci-k",
    "name": "Bi̇leci̇k",
    "districts": [
      "Bozüyük",
      "Gölpazari",
      "İ̇nhi̇sar",
      "Merkez",
      "Osmaneli̇",
      "Pazaryeri̇",
      "Söğüt",
      "Yeni̇pazar"
    ]
  },
  {
    "id": "bi-ngol",
    "name": "Bi̇ngöl",
    "districts": [
      "Adakli",
      "Genç",
      "Karliova",
      "Ki̇ği",
      "Merkez",
      "Solhan",
      "Yayladere",
      "Yedi̇su"
    ]
  },
  {
    "id": "bi-tli-s",
    "name": "Bi̇tli̇s",
    "districts": [
      "Adi̇lcevaz",
      "Ahlat",
      "Güroymak",
      "Hi̇zan",
      "Merkez",
      "Mutki̇",
      "Tatvan"
    ]
  },
  {
    "id": "bolu",
    "name": "Bolu",
    "districts": [
      "Dörtdi̇van",
      "Gerede",
      "Göynük",
      "Kibriscik",
      "Mengen",
      "Merkez",
      "Mudurnu",
      "Seben",
      "Yeni̇çağa"
    ]
  },
  {
    "id": "burdur",
    "name": "Burdur",
    "districts": [
      "Ağlasun",
      "Altinyayla",
      "Bucak",
      "Çavdir",
      "Çelti̇kçi̇",
      "Gölhi̇sar",
      "Karamanli",
      "Kemer",
      "Merkez",
      "Tefenni̇",
      "Yeşi̇lova"
    ]
  },
  {
    "id": "bursa",
    "name": "Bursa",
    "districts": [
      "Büyükorhan",
      "Gemli̇k",
      "Gürsu",
      "Harmancik",
      "İ̇negöl",
      "İ̇zni̇k",
      "Karacabey",
      "Keles",
      "Kestel",
      "Mudanya",
      "Mustafakemalpaşa",
      "Ni̇lüfer",
      "Orhaneli̇",
      "Orhangazi̇",
      "Osmangazi̇",
      "Yeni̇şehi̇r",
      "Yildirim"
    ]
  },
  {
    "id": "canakkale",
    "name": "Çanakkale",
    "districts": [
      "Ayvacik",
      "Bayrami̇ç",
      "Bi̇ga",
      "Bozcaada",
      "Çan",
      "Eceabat",
      "Ezi̇ne",
      "Geli̇bolu",
      "Gökçeada",
      "Lapseki̇",
      "Merkez",
      "Yeni̇ce"
    ]
  },
  {
    "id": "cankiri",
    "name": "Çankiri",
    "districts": [
      "Atkaracalar",
      "Bayramören",
      "Çerkeş",
      "Eldi̇van",
      "İlgaz",
      "Kizilirmak",
      "Korgun",
      "Kurşunlu",
      "Merkez",
      "Orta",
      "Şabanözü",
      "Yaprakli"
    ]
  },
  {
    "id": "corum",
    "name": "Çorum",
    "districts": [
      "Alaca",
      "Bayat",
      "Boğazkale",
      "Dodurga",
      "İ̇ski̇li̇p",
      "Kargi",
      "Laçi̇n",
      "Meci̇tözü",
      "Merkez",
      "Oğuzlar",
      "Ortaköy",
      "Osmancik",
      "Sungurlu",
      "Uğurludağ"
    ]
  },
  {
    "id": "deni-zli",
    "name": "Deni̇zli̇",
    "districts": [
      "Acipayam",
      "Babadağ",
      "Baklan",
      "Beki̇lli̇",
      "Beyağaç",
      "Bozkurt",
      "Buldan",
      "Çal",
      "Çameli̇",
      "Çardak",
      "Çi̇vri̇l",
      "Güney",
      "Honaz",
      "Kale",
      "Merkez",
      "Merkezefendi̇",
      "Pamukkale",
      "Sarayköy",
      "Seri̇nhi̇sar",
      "Tavas"
    ]
  },
  {
    "id": "di-yarbakir",
    "name": "Di̇yarbakir",
    "districts": [
      "Bağlar",
      "Bi̇smi̇l",
      "Çermi̇k",
      "Çinar",
      "Çüngüş",
      "Di̇cle",
      "Eği̇l",
      "Ergani̇",
      "Hani̇",
      "Hazro",
      "Kayapinar",
      "Kocaköy",
      "Kulp",
      "Li̇ce",
      "Merkez",
      "Si̇lvan",
      "Sur",
      "Yeni̇şehi̇r"
    ]
  },
  {
    "id": "duzce",
    "name": "Düzce",
    "districts": [
      "Akçakoca",
      "Cumayeri̇",
      "Çi̇li̇mli̇",
      "Gölyaka",
      "Gümüşova",
      "Kaynaşli",
      "Merkez",
      "Yiğilca"
    ]
  },
  {
    "id": "edi-rne",
    "name": "Edi̇rne",
    "districts": [
      "Enez",
      "Havsa",
      "İ̇psala",
      "Keşan",
      "Lalapaşa",
      "Meri̇ç",
      "Merkez",
      "Süloğlu",
      "Uzunköprü"
    ]
  },
  {
    "id": "elazig",
    "name": "Elaziğ",
    "districts": [
      "Ağin",
      "Alacakaya",
      "Aricak",
      "Baski̇l",
      "Karakoçan",
      "Keban",
      "Kovancilar",
      "Maden",
      "Merkez",
      "Palu",
      "Si̇vri̇ce"
    ]
  },
  {
    "id": "erzi-ncan",
    "name": "Erzi̇ncan",
    "districts": [
      "Çayirli",
      "İ̇li̇ç",
      "Kemah",
      "Kemali̇ye",
      "Merkez",
      "Otlukbeli̇",
      "Refahi̇ye",
      "Tercan",
      "Üzümlü"
    ]
  },
  {
    "id": "erzurum",
    "name": "Erzurum",
    "districts": [
      "Aşkale",
      "Azi̇zi̇ye",
      "Çat",
      "Hinis",
      "Horasan",
      "İ̇spi̇r",
      "Karaçoban",
      "Karayazi",
      "Köprüköy",
      "Merkez",
      "Narman",
      "Oltu",
      "Olur",
      "Palandöken",
      "Pasi̇nler",
      "Pazaryolu",
      "Şenkaya",
      "Tekman",
      "Tortum",
      "Uzundere",
      "Yakuti̇ye"
    ]
  },
  {
    "id": "eski-sehi-r",
    "name": "Eski̇şehi̇r",
    "districts": [
      "Alpu",
      "Beyli̇kova",
      "Çi̇fteler",
      "Günyüzü",
      "Han",
      "İ̇nönü",
      "Mahmudi̇ye",
      "Merkez",
      "Mi̇halgazi̇",
      "Mi̇haliççik",
      "Odunpazari",
      "Saricakaya",
      "Seyi̇tgazi̇",
      "Si̇vri̇hi̇sar",
      "Tepebaşi"
    ]
  },
  {
    "id": "gazi-antep",
    "name": "Gazi̇antep",
    "districts": [
      "Araban",
      "İ̇slahi̇ye",
      "Karkamiş",
      "Merkez",
      "Ni̇zi̇p",
      "Nurdaği",
      "Oğuzeli̇",
      "Şahi̇nbey",
      "Şehi̇tkami̇l",
      "Yavuzeli̇"
    ]
  },
  {
    "id": "gi-resun",
    "name": "Gi̇resun",
    "districts": [
      "Alucra",
      "Bulancak",
      "Çamoluk",
      "Çanakçi",
      "Dereli̇",
      "Doğankent",
      "Espi̇ye",
      "Eynesi̇l",
      "Görele",
      "Güce",
      "Keşap",
      "Merkez",
      "Pi̇razi̇z",
      "Şebi̇nkarahi̇sar",
      "Ti̇rebolu",
      "Yağlidere"
    ]
  },
  {
    "id": "gumushane",
    "name": "Gümüşhane",
    "districts": [
      "Kelki̇t",
      "Köse",
      "Kürtün",
      "Merkez",
      "Şi̇ran",
      "Torul"
    ]
  },
  {
    "id": "hakkari",
    "name": "Hakkari̇",
    "districts": [
      "Çukurca",
      "Merkez",
      "Şemdi̇nli̇",
      "Yüksekova"
    ]
  },
  {
    "id": "hatay",
    "name": "Hatay",
    "districts": [
      "Altinözü",
      "Antakya",
      "Arsuz",
      "Belen",
      "Defne",
      "Dörtyol",
      "Erzi̇n",
      "Hassa",
      "İ̇skenderun",
      "Kirikhan",
      "Kumlu",
      "Merkez",
      "Payas",
      "Reyhanli",
      "Samandağ",
      "Yayladaği"
    ]
  },
  {
    "id": "igdir",
    "name": "İğdir",
    "districts": [
      "Aralik",
      "Karakoyunlu",
      "Merkez",
      "Tuzluca"
    ]
  },
  {
    "id": "isparta",
    "name": "İsparta",
    "districts": [
      "Aksu",
      "Atabey",
      "Eği̇rdi̇r",
      "Gelendost",
      "Gönen",
      "Keçi̇borlu",
      "Merkez",
      "Seni̇rkent",
      "Sütçüler",
      "Şarki̇karaağaç",
      "Uluborlu",
      "Yalvaç",
      "Yeni̇şarbademli̇"
    ]
  },
  {
    "id": "i-stanbul",
    "name": "İ̇stanbul",
    "districts": [
      "Adalar",
      "Arnavutköy",
      "Ataşehi̇r",
      "Avcilar",
      "Bağcilar",
      "Bahçeli̇evler",
      "Bakirköy",
      "Başakşehi̇r",
      "Bayrampaşa",
      "Beşi̇ktaş",
      "Beykoz",
      "Beyli̇kdüzü",
      "Beyoğlu",
      "Büyükçekmece",
      "Çatalca",
      "Çekmeköy",
      "Emi̇nönü",
      "Esenler",
      "Esenyurt",
      "Eyüpsultan",
      "Fati̇h",
      "Gazi̇osmanpaşa",
      "Güngören",
      "Kadiköy",
      "Kağithane",
      "Kartal",
      "Küçükçekmece",
      "Maltepe",
      "Pendi̇k",
      "Sancaktepe",
      "Sariyer",
      "Si̇li̇vri̇",
      "Sultanbeyli̇",
      "Sultangazi̇",
      "Şi̇le",
      "Şi̇şli̇",
      "Tuzla",
      "Ümrani̇ye",
      "Üsküdar",
      "Zeyti̇nburnu"
    ]
  },
  {
    "id": "i-zmi-r",
    "name": "İ̇zmi̇r",
    "districts": [
      "Ali̇ağa",
      "Balçova",
      "Bayindir",
      "Bayrakli",
      "Bergama",
      "Beydağ",
      "Bornova",
      "Buca",
      "Çeşme",
      "Çi̇ğli̇",
      "Di̇ki̇li̇",
      "Foça",
      "Gazi̇emi̇r",
      "Güzelbahçe",
      "Karabağlar",
      "Karaburun",
      "Karşiyaka",
      "Kemalpaşa",
      "Kinik",
      "Ki̇raz",
      "Konak",
      "Menderes",
      "Menemen",
      "Narlidere",
      "Ödemi̇ş",
      "Seferi̇hi̇sar",
      "Selçuk",
      "Ti̇re",
      "Torbali",
      "Urla"
    ]
  },
  {
    "id": "kahramanmaras",
    "name": "Kahramanmaraş",
    "districts": [
      "Afşi̇n",
      "Andirin",
      "Çağlayanceri̇t",
      "Dulkadi̇roğlu",
      "Eki̇nözü",
      "Elbi̇stan",
      "Göksun",
      "Merkez",
      "Nurhak",
      "Oni̇ki̇şubat",
      "Pazarcik",
      "Türkoğlu"
    ]
  },
  {
    "id": "karabuk",
    "name": "Karabük",
    "districts": [
      "Eflani̇",
      "Eski̇pazar",
      "Merkez",
      "Ovacik",
      "Safranbolu",
      "Yeni̇ce"
    ]
  },
  {
    "id": "karaman",
    "name": "Karaman",
    "districts": [
      "Ayranci",
      "Başyayla",
      "Ermenek",
      "Kazimkarabeki̇r",
      "Merkez",
      "Sariveli̇ler"
    ]
  },
  {
    "id": "kars",
    "name": "Kars",
    "districts": [
      "Akyaka",
      "Arpaçay",
      "Di̇gor",
      "Kağizman",
      "Merkez",
      "Sarikamiş",
      "Seli̇m",
      "Susuz"
    ]
  },
  {
    "id": "kastamonu",
    "name": "Kastamonu",
    "districts": [
      "Abana",
      "Ağli",
      "Araç",
      "Azdavay",
      "Bozkurt",
      "Ci̇de",
      "Çatalzeyti̇n",
      "Daday",
      "Devrekani̇",
      "Doğanyurt",
      "Hanönü",
      "İ̇hsangazi̇",
      "İ̇nebolu",
      "Küre",
      "Merkez",
      "Pinarbaşi",
      "Seydi̇ler",
      "Şenpazar",
      "Taşköprü",
      "Tosya"
    ]
  },
  {
    "id": "kayseri",
    "name": "Kayseri̇",
    "districts": [
      "Akkişla",
      "Bünyan",
      "Develi̇",
      "Felahi̇ye",
      "Hacilar",
      "İ̇ncesu",
      "Kocasi̇nan",
      "Meli̇kgazi̇",
      "Özvatan",
      "Pinarbaşi",
      "Sarioğlan",
      "Sariz",
      "Talas",
      "Tomarza",
      "Yahyali",
      "Yeşi̇lhi̇sar"
    ]
  },
  {
    "id": "kirikkale",
    "name": "Kirikkale",
    "districts": [
      "Bahşi̇li̇",
      "Balişeyh",
      "Çelebi̇",
      "Deli̇ce",
      "Karakeçi̇li̇",
      "Keski̇n",
      "Merkez",
      "Sulakyurt",
      "Yahşi̇han"
    ]
  },
  {
    "id": "kirklareli",
    "name": "Kirklareli̇",
    "districts": [
      "Babaeski̇",
      "Demi̇rköy",
      "Kofçaz",
      "Lüleburgaz",
      "Merkez",
      "Pehli̇vanköy",
      "Pinarhi̇sar",
      "Vi̇ze"
    ]
  },
  {
    "id": "kirsehi-r",
    "name": "Kirşehi̇r",
    "districts": [
      "Akçakent",
      "Akpinar",
      "Boztepe",
      "Çi̇çekdaği",
      "Kaman",
      "Merkez",
      "Mucur"
    ]
  },
  {
    "id": "ki-li-s",
    "name": "Ki̇li̇s",
    "districts": [
      "Elbeyli̇",
      "Merkez",
      "Musabeyli̇",
      "Polateli̇"
    ]
  },
  {
    "id": "kocaeli",
    "name": "Kocaeli̇",
    "districts": [
      "Çayirova",
      "Darica",
      "Deri̇nce",
      "Di̇lovasi",
      "Gebze",
      "Gölcük",
      "İ̇zmi̇t",
      "Kandira",
      "Karamürsel",
      "Kartepe",
      "Körfez",
      "Merkez"
    ]
  },
  {
    "id": "konya",
    "name": "Konya",
    "districts": [
      "Ahirli",
      "Akören",
      "Akşehi̇r",
      "Altineki̇n",
      "Beyşehi̇r",
      "Bozkir",
      "Ci̇hanbeyli̇",
      "Çelti̇k",
      "Çumra",
      "Derbent",
      "Derebucak",
      "Doğanhi̇sar",
      "Emi̇rgazi̇",
      "Ereğli̇",
      "Güneysinir",
      "Hadi̇m",
      "Halkapinar",
      "Hüyük",
      "İlgin",
      "Kadinhani",
      "Karapinar",
      "Karatay",
      "Kulu",
      "Meram",
      "Sarayönü",
      "Selçuklu",
      "Seydi̇şehi̇r",
      "Taşkent",
      "Tuzlukçu",
      "Yalihüyük",
      "Yunak"
    ]
  },
  {
    "id": "kutahya",
    "name": "Kütahya",
    "districts": [
      "Altintaş",
      "Aslanapa",
      "Çavdarhi̇sar",
      "Domani̇ç",
      "Dumlupinar",
      "Emet",
      "Gedi̇z",
      "Hi̇sarcik",
      "Merkez",
      "Pazarlar",
      "Si̇mav",
      "Şaphane",
      "Tavşanli"
    ]
  },
  {
    "id": "malatya",
    "name": "Malatya",
    "districts": [
      "Akçadağ",
      "Arapgi̇r",
      "Arguvan",
      "Battalgazi̇",
      "Darende",
      "Doğanşehi̇r",
      "Doğanyol",
      "Heki̇mhan",
      "Kale",
      "Kuluncak",
      "Merkez",
      "Pütürge",
      "Yazihan",
      "Yeşi̇lyurt"
    ]
  },
  {
    "id": "mani-sa",
    "name": "Mani̇sa",
    "districts": [
      "Ahmetli̇",
      "Akhi̇sar",
      "Alaşehi̇r",
      "Demi̇rci̇",
      "Gölmarmara",
      "Gördes",
      "Kirkağaç",
      "Köprübaşi",
      "Kula",
      "Merkez",
      "Sali̇hli̇",
      "Sarigöl",
      "Saruhanli",
      "Selendi̇",
      "Soma",
      "Şehzadeler",
      "Turgutlu",
      "Yunusemre"
    ]
  },
  {
    "id": "mardi-n",
    "name": "Mardi̇n",
    "districts": [
      "Artuklu",
      "Dargeçi̇t",
      "Deri̇k",
      "Kiziltepe",
      "Mazidaği",
      "Merkez",
      "Mi̇dyat",
      "Nusaybi̇n",
      "Ömerli̇",
      "Savur",
      "Yeşi̇lli̇"
    ]
  },
  {
    "id": "mersi-n",
    "name": "Mersi̇n",
    "districts": [
      "Akdeni̇z",
      "Anamur",
      "Aydincik",
      "Bozyazi",
      "Çamliyayla",
      "Erdemli̇",
      "Gülnar",
      "Merkez",
      "Mezi̇tli̇",
      "Mut",
      "Si̇li̇fke",
      "Tarsus",
      "Toroslar",
      "Yeni̇şehi̇r"
    ]
  },
  {
    "id": "mugla",
    "name": "Muğla",
    "districts": [
      "Bodrum",
      "Dalaman",
      "Datça",
      "Fethi̇ye",
      "Kavaklidere",
      "Köyceği̇z",
      "Marmari̇s",
      "Menteşe",
      "Merkez",
      "Mi̇las",
      "Ortaca",
      "Seydi̇kemer",
      "Ula",
      "Yatağan"
    ]
  },
  {
    "id": "mus",
    "name": "Muş",
    "districts": [
      "Bulanik",
      "Hasköy",
      "Korkut",
      "Malazgi̇rt",
      "Merkez",
      "Varto"
    ]
  },
  {
    "id": "nevsehi-r",
    "name": "Nevşehi̇r",
    "districts": [
      "Acigöl",
      "Avanos",
      "Deri̇nkuyu",
      "Gülşehi̇r",
      "Hacibektaş",
      "Kozakli",
      "Merkez",
      "Ürgüp"
    ]
  },
  {
    "id": "ni-gde",
    "name": "Ni̇ğde",
    "districts": [
      "Altunhi̇sar",
      "Bor",
      "Çamardi",
      "Çi̇ftli̇k",
      "Merkez",
      "Ulukişla"
    ]
  },
  {
    "id": "ordu",
    "name": "Ordu",
    "districts": [
      "Akkuş",
      "Altinordu",
      "Aybasti",
      "Çamaş",
      "Çatalpinar",
      "Çaybaşi",
      "Fatsa",
      "Gölköy",
      "Gülyali",
      "Gürgentepe",
      "İ̇ki̇zce",
      "Kabadüz",
      "Kabataş",
      "Korgan",
      "Kumru",
      "Merkez",
      "Mesudi̇ye",
      "Perşembe",
      "Ulubey",
      "Ünye"
    ]
  },
  {
    "id": "osmani-ye",
    "name": "Osmani̇ye",
    "districts": [
      "Bahçe",
      "Düzi̇çi̇",
      "Hasanbeyli̇",
      "Kadi̇rli̇",
      "Merkez",
      "Sumbas",
      "Toprakkale"
    ]
  },
  {
    "id": "ri-ze",
    "name": "Ri̇ze",
    "districts": [
      "Ardeşen",
      "Çamlihemşi̇n",
      "Çayeli̇",
      "Derepazari",
      "Findikli",
      "Güneysu",
      "Hemşi̇n",
      "İ̇ki̇zdere",
      "İ̇yi̇dere",
      "Kalkandere",
      "Merkez",
      "Pazar"
    ]
  },
  {
    "id": "sakarya",
    "name": "Sakarya",
    "districts": [
      "Adapazari",
      "Akyazi",
      "Ari̇fi̇ye",
      "Erenler",
      "Feri̇zli̇",
      "Geyve",
      "Hendek",
      "Karapürçek",
      "Karasu",
      "Kaynarca",
      "Kocaali̇",
      "Merkez",
      "Pamukova",
      "Sapanca",
      "Serdi̇van",
      "Söğütlü",
      "Tarakli"
    ]
  },
  {
    "id": "samsun",
    "name": "Samsun",
    "districts": [
      "19 Mayis",
      "Alaçam",
      "Asarcik",
      "Atakum",
      "Ayvacik",
      "Bafra",
      "Cani̇k",
      "Çarşamba",
      "Havza",
      "İ̇lkadim",
      "Kavak",
      "Ladi̇k",
      "Merkez",
      "Salipazari",
      "Tekkeköy",
      "Terme",
      "Vezi̇rköprü",
      "Yakakent"
    ]
  },
  {
    "id": "si-i-rt",
    "name": "Si̇i̇rt",
    "districts": [
      "Baykan",
      "Eruh",
      "Kurtalan",
      "Merkez",
      "Pervari̇",
      "Şi̇rvan",
      "Ti̇llo"
    ]
  },
  {
    "id": "si-nop",
    "name": "Si̇nop",
    "districts": [
      "Ayancik",
      "Boyabat",
      "Di̇kmen",
      "Durağan",
      "Erfelek",
      "Gerze",
      "Merkez",
      "Saraydüzü",
      "Türkeli̇"
    ]
  },
  {
    "id": "si-vas",
    "name": "Si̇vas",
    "districts": [
      "Akincilar",
      "Altinyayla",
      "Di̇vri̇ği̇",
      "Doğanşar",
      "Gemerek",
      "Gölova",
      "Gürün",
      "Hafi̇k",
      "İ̇mranli",
      "Kangal",
      "Koyulhi̇sar",
      "Merkez",
      "Suşehri̇",
      "Şarkişla",
      "Ulaş",
      "Yildizeli̇",
      "Zara"
    ]
  },
  {
    "id": "sanliurfa",
    "name": "Şanliurfa",
    "districts": [
      "Akçakale",
      "Bi̇reci̇k",
      "Bozova",
      "Ceylanpinar",
      "Eyyübi̇ye",
      "Halfeti̇",
      "Hali̇li̇ye",
      "Harran",
      "Hi̇lvan",
      "Karaköprü",
      "Merkez",
      "Si̇verek",
      "Suruç",
      "Vi̇ranşehi̇r"
    ]
  },
  {
    "id": "sirnak",
    "name": "Şirnak",
    "districts": [
      "Beytüşşebap",
      "Ci̇zre",
      "Güçlükonak",
      "İ̇di̇l",
      "Merkez",
      "Si̇lopi̇",
      "Uludere"
    ]
  },
  {
    "id": "teki-rdag",
    "name": "Teki̇rdağ",
    "districts": [
      "Çerkezköy",
      "Çorlu",
      "Ergene",
      "Hayrabolu",
      "Kapakli",
      "Malkara",
      "Marmaraereğli̇si̇",
      "Merkez",
      "Muratli",
      "Saray",
      "Süleymanpaşa",
      "Şarköy"
    ]
  },
  {
    "id": "tokat",
    "name": "Tokat",
    "districts": [
      "Almus",
      "Artova",
      "Başçi̇ftli̇k",
      "Erbaa",
      "Merkez",
      "Ni̇ksar",
      "Pazar",
      "Reşadi̇ye",
      "Sulusaray",
      "Turhal",
      "Yeşi̇lyurt",
      "Zi̇le"
    ]
  },
  {
    "id": "trabzon",
    "name": "Trabzon",
    "districts": [
      "Akçaabat",
      "Arakli",
      "Arsi̇n",
      "Beşi̇kdüzü",
      "Çarşibaşi",
      "Çaykara",
      "Dernekpazari",
      "Düzköy",
      "Hayrat",
      "Köprübaşi",
      "Maçka",
      "Merkez",
      "Of",
      "Ortahi̇sar",
      "Sürmene",
      "Şalpazari",
      "Tonya",
      "Vakfikebi̇r",
      "Yomra"
    ]
  },
  {
    "id": "tunceli",
    "name": "Tunceli̇",
    "districts": [
      "Çemi̇şgezek",
      "Hozat",
      "Mazgi̇rt",
      "Merkez",
      "Nazimi̇ye",
      "Ovacik",
      "Pertek",
      "Pülümür"
    ]
  },
  {
    "id": "usak",
    "name": "Uşak",
    "districts": [
      "Banaz",
      "Eşme",
      "Karahalli",
      "Merkez",
      "Si̇vasli",
      "Ulubey"
    ]
  },
  {
    "id": "van",
    "name": "Van",
    "districts": [
      "Bahçesaray",
      "Başkale",
      "Çaldiran",
      "Çatak",
      "Edremi̇t",
      "Erci̇ş",
      "Gevaş",
      "Gürpinar",
      "İ̇pekyolu",
      "Merkez",
      "Muradi̇ye",
      "Özalp",
      "Saray",
      "Tuşba"
    ]
  },
  {
    "id": "yalova",
    "name": "Yalova",
    "districts": [
      "Altinova",
      "Armutlu",
      "Çinarcik",
      "Çi̇ftli̇kköy",
      "Merkez",
      "Termal"
    ]
  },
  {
    "id": "yozgat",
    "name": "Yozgat",
    "districts": [
      "Akdağmadeni̇",
      "Aydincik",
      "Boğazliyan",
      "Çandir",
      "Çayiralan",
      "Çekerek",
      "Kadişehri̇",
      "Merkez",
      "Saraykent",
      "Sarikaya",
      "Sorgun",
      "Şefaatli̇",
      "Yeni̇fakili",
      "Yerköy"
    ]
  },
  {
    "id": "zonguldak",
    "name": "Zonguldak",
    "districts": [
      "Alapli",
      "Çaycuma",
      "Devrek",
      "Ereğli̇",
      "Gökçebey",
      "Ki̇li̇mli̇",
      "Kozlu",
      "Merkez"
    ]
  }
] as const;

export type City = (typeof CITIES)[number];
